title: What is pressure?
hero_image: images/banner.png
description: Find out all about pressure
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 # 1, 2 or 3
ingredient: true
listed: false
steps:
  - title: Step one
